name: "CI/CD Pipeline"
on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    paths:
      - '*/**'
  push:
    branches: [ main ]
    paths:
      - '*/**'

jobs:
  build:
    uses: devops4solutions/github-reusable-workflows/blob/main/ci.yaml@main
    with:
      working-directory: terraform
      ecr-registry: public.ecr.aws/w0f5g4k6
      ecr-repository: hello-svc
      image-tag: ${{ github.sha }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  #terraform:
   # needs: build
   ## uses: devops4solutions/github-reusable-workflows/.github/workflows/cd.yaml@main
    #with:
    #  working-directory: terraform
    #secrets:
    #  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
     # AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
